require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlayerTanksController do

  # This should return the minimal set of attributes required to create a valid
  # PlayerTank. As you add validations to PlayerTank, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "player_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlayerTanksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all player_tanks as @player_tanks" do
      player_tank = PlayerTank.create! valid_attributes
      get :index, {}, valid_session
      assigns(:player_tanks).should eq([player_tank])
    end
  end

  describe "GET show" do
    it "assigns the requested player_tank as @player_tank" do
      player_tank = PlayerTank.create! valid_attributes
      get :show, {:id => player_tank.to_param}, valid_session
      assigns(:player_tank).should eq(player_tank)
    end
  end

  describe "GET new" do
    it "assigns a new player_tank as @player_tank" do
      get :new, {}, valid_session
      assigns(:player_tank).should be_a_new(PlayerTank)
    end
  end

  describe "GET edit" do
    it "assigns the requested player_tank as @player_tank" do
      player_tank = PlayerTank.create! valid_attributes
      get :edit, {:id => player_tank.to_param}, valid_session
      assigns(:player_tank).should eq(player_tank)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlayerTank" do
        expect {
          post :create, {:player_tank => valid_attributes}, valid_session
        }.to change(PlayerTank, :count).by(1)
      end

      it "assigns a newly created player_tank as @player_tank" do
        post :create, {:player_tank => valid_attributes}, valid_session
        assigns(:player_tank).should be_a(PlayerTank)
        assigns(:player_tank).should be_persisted
      end

      it "redirects to the created player_tank" do
        post :create, {:player_tank => valid_attributes}, valid_session
        response.should redirect_to(PlayerTank.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved player_tank as @player_tank" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlayerTank.any_instance.stub(:save).and_return(false)
        post :create, {:player_tank => { "player_id" => "invalid value" }}, valid_session
        assigns(:player_tank).should be_a_new(PlayerTank)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlayerTank.any_instance.stub(:save).and_return(false)
        post :create, {:player_tank => { "player_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested player_tank" do
        player_tank = PlayerTank.create! valid_attributes
        # Assuming there are no other player_tanks in the database, this
        # specifies that the PlayerTank created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlayerTank.any_instance.should_receive(:update).with({ "player_id" => "1" })
        put :update, {:id => player_tank.to_param, :player_tank => { "player_id" => "1" }}, valid_session
      end

      it "assigns the requested player_tank as @player_tank" do
        player_tank = PlayerTank.create! valid_attributes
        put :update, {:id => player_tank.to_param, :player_tank => valid_attributes}, valid_session
        assigns(:player_tank).should eq(player_tank)
      end

      it "redirects to the player_tank" do
        player_tank = PlayerTank.create! valid_attributes
        put :update, {:id => player_tank.to_param, :player_tank => valid_attributes}, valid_session
        response.should redirect_to(player_tank)
      end
    end

    describe "with invalid params" do
      it "assigns the player_tank as @player_tank" do
        player_tank = PlayerTank.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlayerTank.any_instance.stub(:save).and_return(false)
        put :update, {:id => player_tank.to_param, :player_tank => { "player_id" => "invalid value" }}, valid_session
        assigns(:player_tank).should eq(player_tank)
      end

      it "re-renders the 'edit' template" do
        player_tank = PlayerTank.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlayerTank.any_instance.stub(:save).and_return(false)
        put :update, {:id => player_tank.to_param, :player_tank => { "player_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested player_tank" do
      player_tank = PlayerTank.create! valid_attributes
      expect {
        delete :destroy, {:id => player_tank.to_param}, valid_session
      }.to change(PlayerTank, :count).by(-1)
    end

    it "redirects to the player_tanks list" do
      player_tank = PlayerTank.create! valid_attributes
      delete :destroy, {:id => player_tank.to_param}, valid_session
      response.should redirect_to(player_tanks_url)
    end
  end

end
