require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TanksController do

=begin
  # This should return the minimal set of attributes required to create a valid
  # Tank. As you add validations to Tank, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TanksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tanks as @tanks" do
      tank = Tank.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tanks).should eq([tank])
    end
  end

  describe "GET show" do
    it "assigns the requested tank as @tank" do
      tank = Tank.create! valid_attributes
      get :show, {:id => tank.to_param}, valid_session
      assigns(:tank).should eq(tank)
    end
  end

  describe "GET new" do
    it "assigns a new tank as @tank" do
      get :new, {}, valid_session
      assigns(:tank).should be_a_new(Tank)
    end
  end

  describe "GET edit" do
    it "assigns the requested tank as @tank" do
      tank = Tank.create! valid_attributes
      get :edit, {:id => tank.to_param}, valid_session
      assigns(:tank).should eq(tank)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tank" do
        expect {
          post :create, {:tank => valid_attributes}, valid_session
        }.to change(Tank, :count).by(1)
      end

      it "assigns a newly created tank as @tank" do
        post :create, {:tank => valid_attributes}, valid_session
        assigns(:tank).should be_a(Tank)
        assigns(:tank).should be_persisted
      end

      it "redirects to the created tank" do
        post :create, {:tank => valid_attributes}, valid_session
        response.should redirect_to(Tank.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tank as @tank" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tank.any_instance.stub(:save).and_return(false)
        post :create, {:tank => { "name" => "invalid value" }}, valid_session
        assigns(:tank).should be_a_new(Tank)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tank.any_instance.stub(:save).and_return(false)
        post :create, {:tank => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tank" do
        tank = Tank.create! valid_attributes
        # Assuming there are no other tanks in the database, this
        # specifies that the Tank created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tank.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => tank.to_param, :tank => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested tank as @tank" do
        tank = Tank.create! valid_attributes
        put :update, {:id => tank.to_param, :tank => valid_attributes}, valid_session
        assigns(:tank).should eq(tank)
      end

      it "redirects to the tank" do
        tank = Tank.create! valid_attributes
        put :update, {:id => tank.to_param, :tank => valid_attributes}, valid_session
        response.should redirect_to(tank)
      end
    end

    describe "with invalid params" do
      it "assigns the tank as @tank" do
        tank = Tank.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tank.any_instance.stub(:save).and_return(false)
        put :update, {:id => tank.to_param, :tank => { "name" => "invalid value" }}, valid_session
        assigns(:tank).should eq(tank)
      end

      it "re-renders the 'edit' template" do
        tank = Tank.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tank.any_instance.stub(:save).and_return(false)
        put :update, {:id => tank.to_param, :tank => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tank" do
      tank = Tank.create! valid_attributes
      expect {
        delete :destroy, {:id => tank.to_param}, valid_session
      }.to change(Tank, :count).by(-1)
    end

    it "redirects to the tanks list" do
      tank = Tank.create! valid_attributes
      delete :destroy, {:id => tank.to_param}, valid_session
      response.should redirect_to(tanks_url)
    end
  end
=end

end
